Repository 5tarlight/jamza, pull requests merged in 2022-07, with the labels that each got.

#1 F/y/console
  build.gradle
  run.sh
  src/main/java/com/yeahx4/jamza/Jamza.java
  src/main/java/com/yeahx4/jamza/util/Console.java
  src/main/java/com/yeahx4/jamza/util/ConsoleColor.java
Labels: size/L

#2 F/h/console input
  build.gradle
  src/main/java/com/yeahx4/jamza/Jamza.java
  src/main/java/com/yeahx4/jamza/util/Console.java
Labels: size/M

#5 F/h/console util
  src/main/java/com/yeahx4/jamza/Jamza.java
  src/main/java/com/yeahx4/jamza/util/ColorText.java
  src/main/java/com/yeahx4/jamza/util/Console.java
  src/main/java/com/yeahx4/jamza/util/ConsoleColor.java
  src/test/java/ColorTextTest.java
Labels: size/L

#6 F/h/color text
  src/main/java/com/yeahx4/jamza/Jamza.java
  src/main/java/com/yeahx4/jamza/util/ColorText.java
  src/main/java/com/yeahx4/jamza/util/Console.java
  src/test/java/ColorTextTest.java
Labels: size/M

#7 Main Menu Update
  build.gradle
  run.sh
  src/main/java/com/yeahx4/jamza/Jamza.java
  src/main/java/com/yeahx4/jamza/util/ColorText.java
  src/main/java/com/yeahx4/jamza/util/Console.java
  src/main/java/com/yeahx4/jamza/util/ConsoleColor.java
  src/test/java/ColorTextTest.java
Labels: size/L

#12 Player file system loading
  .gitignore
  build.gradle
  run.sh
  src/main/java/com/yeahx4/jamza/Jamza.java
  src/main/java/com/yeahx4/jamza/champion/Champion.java
  src/main/java/com/yeahx4/jamza/champion/Champions.java
  src/main/java/com/yeahx4/jamza/champion/Entity.java
  src/main/java/com/yeahx4/jamza/champion/Player.java
  src/main/java/com/yeahx4/jamza/champion/Warrior.java
  src/main/java/com/yeahx4/jamza/util/Console.java
  src/test/java/ColorTextTest.java
Labels: size/XL

#13 Map
  src/main/java/com/yeahx4/jamza/Jamza.java
  src/main/java/com/yeahx4/jamza/champion/Champion.java
  src/main/java/com/yeahx4/jamza/champion/Player.java
  src/main/java/com/yeahx4/jamza/map/Map.java
  src/main/java/com/yeahx4/jamza/map/Maps.java
  src/main/java/com/yeahx4/jamza/map/TestMap.java
  src/main/java/com/yeahx4/jamza/util/ColorText.java
  src/main/java/com/yeahx4/jamza/util/Console.java
Labels: size/L
